CREATE TABLE [dbo].[Client_Product]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ClientId] INT NOT NULL, 
    [ProductId] INT NOT NULL,

    CONSTRAINT FK_CLIENT_CLIENT_PRODUCT FOREIGN KEY ([ClientId]) REFERENCES [Client]([Id]) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUCT_CLIENT_PRODUCT FOREIGN KEY ([ProductId]) REFERENCES [Product]([Id]) ON DELETE CASCADE
)
