CREATE VIEW [dbo].[LigneDeCommandeProduct]
	AS
  SELECT
  [Id],
  [ProductName] ,
  [Total] , 
  [Quantite] , 
  [HTVA] , 
  [TVAC], 
  l.[ProductId] AS LigneProductID,
  [CommandeId] ,
  p.ProductID,
  p.Nom,
  p.IsActif,
  p.Prix,
  p.PrixDAchatHTVA,
  p.TVA,
  p.Details,
  p.CategorieId,
  p.ClientId,
  p.NbPiece,
  CatNom,
  CatIsActif,
  CatDetails,
  CatID,
  FournisseurID,
  FournisseurNom,
  p.Prenom,
  p.Login,
  ClientIsActif,
  p.AdresseId,
  p.NumBCE,
  p.AdRue,
  p.AdNum,
  p.AdCp,
  p.AdVille,
  p.AdPays,
  p.NumTel,
  p.EMail
  FROM LignesDeCommandes l INNER JOIN ProduitCategorie p ON l.ProductId = p.ProductID
